public class Biologist {
byte cellSize = 10;
short experimentTime = 30;
int biologistId = 456;
long dnaSequence = 1234567890L;
float proteinConcentration = 0.5f;
double microbialGrowthRate = 1.2;
char cellType = 'B';
boolean isLabManager = false;
byte numberOfExperiments = 12;
short yearsOfResearch = 8;
int numberOfPublications = 5;
long grantAmount = 500000L;
float enzymeActivity = 0.9f;
double biologicalHalfLife = 36.0;
char biologicalProcess = 'M';
boolean hasDiscoveredNewSpecies = true;
byte numberOfAwardsReceived = 2;
