ublic class Athlete {
byte jerseyNumber = 12;
short minutesPlayed = 45;
int athleteId = 789;
long teamId = 1234567890L;
float speed = 25.5f;
double jumpHeight = 6.8;
char position = 'G';
boolean isCaptain = true;
byte numberOfGoals = 10;
short yearsOfExperience = 5;
int numberOfAssists = 8;
long sportsEquipmentId = 9876543210L;
float enduranceLevel = 0.7f;
double reactionTime = 2.5;
char sport = 'S';
boolean hasWonChampionship = false;
byte numberOfAwards = 3;
}