public class Student {

    int studentId;
    String firstName;
    String lastName;
    int age;
    String gender;
    String grade;
    double gpa;
    String major;
    String minor;
    int credits;
    String email;
    String phoneNumber;
    String address;


    static int studentIdStatic;
    static String firstNameStatic;
    static String lastNameStatic;
    static int ageStatic;
    static String genderStatic;
    static String gradeStatic;
    static double gpaStatic;
    static String majorStatic;
    static String minorStatic;
    static int creditsStatic;
    static String emailStatic;
    static String phoneNumberStatic;
    static String addressStatic;


    public Student() {}


    public static void main(String[] args) {
        Student student1 = new Student();
        student1.studentId = 1001;
        student1.firstName = "John";
        student1.lastName = "Doe";
        student1.age = 20;
        student1.gender = "Male";
        student1.grade = "A";
        student1.gpa = 3.8;
        student1.major = "Computer Science";
        student1.minor = "Mathematics";
        student1.credits = 45;
        student1.email = "john.doe@example.com";
        student1.phoneNumber = "555-1234";
        student1.address = "123 Main St";

        Student student2 = new Student();
        student2.studentId = 1002;
        student2.firstName = "Jane";
        student2.lastName = "Smith";
        student2.age = 21;
        student2.gender = "Female";
        student2.grade = "B+";
        student2.gpa = 3.5;
        student2.major = "Biology";
        student2.minor = "Chemistry";
        student2.credits = 40;
        student2.email = "jane.smith@example.com";
        student2.phoneNumber = "555-5678";
        student2.address = "456 Oak Rd";
		
		Student student3 = new Student();
student3.studentId = 1003;
student3.firstName = "Jane";
student3.lastName = "Smith";
student3.age = 21;
student3.gender = "Female";
student3.grade = "B+";
student3.gpa = 3.5;
student3.major = "Biology";
student3.minor = "Chemistry";
student3.credits = 40;
student3.email = "jane.smith@example.com";
student3.phoneNumber = "555-5678";
student3.address = "456 Oak Rd";


Student student4 = new Student();
student4.studentId = 1004;
student4.firstName = "Jane";
student4.lastName = "Smith";
student4.age = 21;
student4.gender = "Female";
student4.grade = "B+";
student4.gpa = 3.5;
student4.major = "Biology";
student4.minor = "Chemistry";
student4.credits = 40;
student4.email = "jane.smith@example.com";
student4.phoneNumber = "555-5678";
student4.address = "456 Oak Rd";

Student student5 = new Student();
student5.studentId = 1005;
student5.firstName = "Jane";
student5.lastName = "Smith";
student5.age = 21;
student5.gender = "Female";
student5.grade = "B+";
student5.gpa = 3.5;
student5.major = "Biology";
student5.minor = "Chemistry";
student5.credits = 40;
student5.email = "jane.smith@example.com";
student5.phoneNumber = "555-5678";
student5.address = "456 Oak Rd";

Student student6 = new Student();
student6.studentId = 1006;
student6.firstName = "Jane";
student6.lastName = "Smith";
student6.age = 21;
student6.gender = "Female";
student6.grade = "B+";
student6.gpa = 3.5;
student6.major = "Biology";
student6.minor = "Chemistry";
student6.credits = 40;
student6.email = "jane.smith@example.com";
student6.phoneNumber = "555-5678";
student6.address = "456 Oak Rd";

Student student7 = new Student();
student7.studentId = 1007;
student7.firstName = "Jane";
student7.lastName = "Smith";
student7.age = 21;
student7.gender = "Female";
student7.grade = "B+";
student7.gpa = 3.5;
student7.major = "Biology";
student7.minor = "Chemistry";
student7.credits = 40;
student7.email = "jane.smith@example.com";
student7.phoneNumber = "555-5678";
student7.address = "456 Oak Rd";

Student student8 = new Student();
student8.studentId = 1008;
student8.firstName = "Jane";
student8.lastName = "Smith";
student8.age = 21;
student8.gender = "Female";
student8.grade = "B+";
student8.gpa = 3.5;
student8.major = "Biology";
student8.minor = "Chemistry";
student8.credits = 40;
student8.email = "jane.smith@example.com";
student8.phoneNumber = "555-5678";
student8.address = "456 Oak Rd";

Student student9 = new Student();
student9.studentId = 1009;
student9.firstName = "Jane";
student9.lastName = "Smith";
student9.age = 21;
student9.gender = "Female";
student9.grade = "B+";
student9.gpa = 3.5;
student9.major = "Biology";
student9.minor = "Chemistry";
student9.credits = 40;
student9.email = "jane.smith@example.com";
student9.phoneNumber = "555-5678";
student9.address = "456 Oak Rd";

Student student10 = new Student();
student10.studentId = 1010;
student10.firstName = "Jane";
student10.lastName = "Smith";
student10.age = 21;
student10.gender = "Female";
student10.grade = "B+";
student10.gpa = 3.5;
student10.major = "Biology";
student10.minor = "Chemistry";
student10.credits = 40;
student10.email = "jane.smith@example.com";
student10.phoneNumber = "555-5678";
student10.address = "456 Oak Rd";

Student student11 = new Student();
student11.studentId = 1011;
student11.firstName = "Jane";
student11.lastName = "Smith";
student11.age = 21;
student11.gender = "Female";
student11.grade = "B+";
student11.gpa = 3.5;
student11.major = "Biology";
student11.minor = "Chemistry";
student11.credits = 40;
student11.email = "jane.smith@example.com";
student11.phoneNumber = "555-5678";
student11.address = "456 Oak Rd";


Student student12 = new Student();
student12.studentId = 1012;
student12.firstName = "Jane";
student12.lastName = "Smith";
student12.age = 21;
student12.gender = "Female";
student12.grade = "B+";
student12.gpa = 3.5;
student12.major = "Biology";
student12.minor = "Chemistry";
student12.credits = 40;
student12.email = "jane.smith@example.com";
student12.phoneNumber = "555-5678";
student12.address = "456 Oak Rd";

Student student13 = new Student();
student13.studentId = 1013;
student13.firstName = "Jane";
student13.lastName = "Smith";
student13.age = 21;
student13.gender = "Female";
student13.grade = "B+";
student13.gpa = 3.5;
student13.major = "Biology";
student13.minor = "Chemistry";
student13.credits = 40;
student13.email = "jane.smith@example.com";
student13.phoneNumber = "555-5678";
student13.address = "456 Oak Rd";

Student student14 = new Student();
student14.studentId = 1014;
student14.firstName = "Jane";
student14.lastName = "Smith";
student14.age = 21;
student14.gender = "Female";
student14.grade = "B+";
student14.gpa = 3.5;
student14.major = "Biology";
student14.minor = "Chemistry";
student14.credits = 40;
student14.email = "jane.smith@example.com";
student14.phoneNumber = "555-5678";
student14.address = "456 Oak Rd";

Student student15 = new Student();
student15.studentId = 1015;
student15.firstName = "Jane";
student15.lastName = "Smith";
student15.age = 21;
student15.gender = "Female";
student15.grade = "B+";
student15.gpa = 3.5;
student15.major = "Biology";
student15.minor = "Chemistry";
student15.credits = 40;
student15.email = "jane.smith@example.com";
student15.phoneNumber = "555-5678";
student15.address = "456 Oak Rd";

Student student16 = new Student();
student16.studentId = 1016;
student16.firstName = "Jane";
student16.lastName = "Smith";
student16.age = 21;
student16.gender = "Female";
student16.grade = "B+";
student16.gpa = 3.5;
student16.major = "Biology";
student16.minor = "Chemistry";
student16.credits = 40;
student16.email = "jane.smith@example.com";
student16.phoneNumber = "555-5678";
student16.address = "456 Oak Rd";

Student student17 = new Student();
student17.studentId = 1017;
student17.firstName = "Jane";
student17.lastName = "Smith";
student17.age = 21;
student17.gender = "Female";
student17.grade = "B+";
student17.gpa = 3.5;
student17.major = "Biology";
student17.minor = "Chemistry";
student17.credits = 40;
student17.email = "jane.smith@example.com";
student17.phoneNumber = "555-5678";
student17.address = "456 Oak Rd";


student1.studentIdStatic = 1017;
student1.firstNameStatic = "Jane";
student1.lastNameStatic = "Smith";
student1.ageStatic = 21;
student1.genderStatic = "Female";
student1.gradeStatic = "B+";
student1.gpaStatic = 3.5;
student1.majorStatic = "Biology";
student1.minorStatic = "Chemistry";
student1.creditsStatic = 40;
student1.emailStatic = "jane.smith@example.com";
student1.phoneNumberStatic = "555-5678";
student1.addressStatic = "456 Oak Rd";

student2.studentIdStatic = 1017;
student2.firstNameStatic = "Jane";
student2.lastNameStatic = "Smith";
student2.ageStatic = 21;
student2.genderStatic = "Female";
student2.gradeStatic = "B+";
student2.gpaStatic = 3.5;
student2.majorStatic = "Biology";
student2.minorStatic = "Chemistry";
student2.creditsStatic = 40;
student2.emailStatic = "jane.smith@example.com";
student2.phoneNumberStatic = "555-5678";
student2.addressStatic = "456 Oak Rd";

student3.studentIdStatic = 1017;
student3.firstNameStatic = "Jane";
student3.lastNameStatic = "Smith";
student3.ageStatic = 21;
student3.genderStatic = "Female";
student3.gradeStatic = "B+";
student3.gpaStatic = 3.5;
student3.majorStatic = "Biology";
student3.minorStatic = "Chemistry";
student3.creditsStatic = 40;
student3.emailStatic = "jane.smith@example.com";
student3.phoneNumberStatic = "555-5678";
student3.addressStatic = "456 Oak Rd";

student4.studentIdStatic = 1017;
student4.firstNameStatic = "Jane";
student4.lastNameStatic = "Smith";
student4.ageStatic = 21;
student4.genderStatic = "Female";
student4.gradeStatic = "B+";
student4.gpaStatic = 3.5;
student4.majorStatic = "Biology";
student4.minorStatic = "Chemistry";
student4.creditsStatic = 40;
student4.emailStatic = "jane.smith@example.com";
student4.phoneNumberStatic = "555-5678";
student4.addressStatic = "456 Oak Rd";


student5.studentIdStatic = 1017;
student5.firstNameStatic = "Jane";
student5.lastNameStatic = "Smith";
student5.ageStatic = 21;
student5.genderStatic = "Female";
student5.gradeStatic = "B+";
student5.gpaStatic = 3.5;
student5.majorStatic = "Biology";
student5.minorStatic = "Chemistry";
student5.creditsStatic = 40;
student5.emailStatic = "jane.smith@example.com";
student5.phoneNumberStatic = "555-5678";
student5.addressStatic = "456 Oak Rd";

student6.studentIdStatic = 1017;
student6.firstNameStatic = "Jane";
student6.lastNameStatic = "Smith";
student6.ageStatic = 21;
student6.genderStatic = "Female";
student6.gradeStatic = "B+";
student6.gpaStatic = 3.5;
student6.majorStatic = "Biology";
student6.minorStatic = "Chemistry";
student6.creditsStatic = 40;
student6.emailStatic = "jane.smith@example.com";
student6.phoneNumberStatic = "555-5678";
student6.addressStatic = "456 Oak Rd";

student7.studentIdStatic = 1017;
student7.firstNameStatic = "Jane";
student7.lastNameStatic = "Smith";
student7.ageStatic = 21;
student7.genderStatic = "Female";
student7.gradeStatic = "B+";
student7.gpaStatic = 3.5;
student7.majorStatic = "Biology";
student7.minorStatic = "Chemistry";
student7.creditsStatic = 40;
student7.emailStatic = "jane.smith@example.com";
student7.phoneNumberStatic = "555-5678";
student7.addressStatic = "456 Oak Rd";

student8.studentIdStatic = 1017;
student8.firstNameStatic = "Jane";
student8.lastNameStatic = "Smith";
student8.ageStatic = 21;
student8.genderStatic = "Female";
student8.gradeStatic = "B+";
student8.gpaStatic = 3.5;
student8.majorStatic = "Biology";
student8.minorStatic = "Chemistry";
student8.creditsStatic = 40;
student8.emailStatic = "jane.smith@example.com";
student8.phoneNumberStatic = "555-5678";
student8.addressStatic = "456 Oak Rd";

student9.studentIdStatic = 1017;
student9.firstNameStatic = "Jane";
student9.lastNameStatic = "Smith";
student9.ageStatic = 21;
student9.genderStatic = "Female";
student9.gradeStatic = "B+";
student9.gpaStatic = 3.5;
student9.majorStatic = "Biology";
student9.minorStatic = "Chemistry";
student9.creditsStatic = 40;
student9.emailStatic = "jane.smith@example.com";
student9.phoneNumberStatic = "555-5678";
student9.addressStatic = "456 Oak Rd";

student10.studentIdStatic = 1017;
student10.firstNameStatic = "Jane";
student10.lastNameStatic = "Smith";
student10.ageStatic = 21;
student10.genderStatic = "Female";
student10.gradeStatic = "B+";
student10.gpaStatic = 3.5;
student10.majorStatic = "Biology";
student10.minorStatic = "Chemistry";
student10.creditsStatic = 40;
student10.emailStatic = "jane.smith@example.com";
student10.phoneNumberStatic = "555-5678";
student10.addressStatic = "456 Oak Rd";


student11.studentIdStatic = 1017;
student11.firstNameStatic = "Jane";
student11.lastNameStatic = "Smith";
student11.ageStatic = 21;
student11.genderStatic = "Female";
student11.gradeStatic = "B+";
student11.gpaStatic = 3.5;
student11.majorStatic = "Biology";
student11.minorStatic = "Chemistry";
student11.creditsStatic = 40;
student11.emailStatic = "jane.smith@example.com";
student11.phoneNumberStatic = "555-5678";
student11.addressStatic = "456 Oak Rd";

student12.studentIdStatic = 1017;
student12.firstNameStatic = "Jane";
student12.lastNameStatic = "Smith";
student12.ageStatic = 21;
student12.genderStatic = "Female";
student12.gradeStatic = "B+";
student12.gpaStatic = 3.5;
student12.majorStatic = "Biology";
student12.minorStatic = "Chemistry";
student12.creditsStatic = 40;
student12.emailStatic = "jane.smith@example.com";
student12.phoneNumberStatic = "555-5678";
student12.addressStatic = "456 Oak Rd";

student13.studentIdStatic = 1017;
student13.firstNameStatic = "Jane";
student13.lastNameStatic = "Smith";
student13.ageStatic = 21;
student13.genderStatic = "Female";
student13.gradeStatic = "B+";
student13.gpaStatic = 3.5;
student13.majorStatic = "Biology";
student13.minorStatic = "Chemistry";
student13.creditsStatic = 40;
student13.emailStatic = "jane.smith@example.com";
student13.phoneNumberStatic = "555-5678";
student13.addressStatic = "456 Oak Rd";

student14.studentIdStatic = 1017;
student14.firstNameStatic = "Jane";
student14.lastNameStatic = "Smith";
student14.ageStatic = 21;
student14.genderStatic = "Female";
student14.gradeStatic = "B+";
student14.gpaStatic = 3.5;
student14.majorStatic = "Biology";
student14.minorStatic = "Chemistry";
student14.creditsStatic = 40;
student14.emailStatic = "jane.smith@example.com";
student14.phoneNumberStatic = "555-5678";
student14.addressStatic = "456 Oak Rd";

student15.studentIdStatic = 1017;
student15.firstNameStatic = "Jane";
student15.lastNameStatic = "Smith";
student15.ageStatic = 21;
student15.genderStatic = "Female";
student15.gradeStatic = "B+";
student15.gpaStatic = 3.5;
student15.majorStatic = "Biology";
student15.minorStatic = "Chemistry";
student15.creditsStatic = 40;
student15.emailStatic = "jane.smith@example.com";
student15.phoneNumberStatic = "555-5678";
student15.addressStatic = "456 Oak Rd";

student16.studentIdStatic = 1017;
student16.firstNameStatic = "Jane";
student16.lastNameStatic = "Smith";
student16.ageStatic = 21;
student16.genderStatic = "Female";
student16.gradeStatic = "B+";
student16.gpaStatic = 3.5;
student16.majorStatic = "Biology";
student16.minorStatic = "Chemistry";
student16.creditsStatic = 40;
student16.emailStatic = "jane.smith@example.com";
student16.phoneNumberStatic = "555-5678";
student16.addressStatic = "456 Oak Rd";

student17.studentIdStatic = 1017;
student17.firstNameStatic = "Jane";
student17.lastNameStatic = "Smith";
student17.ageStatic = 21;
student17.genderStatic = "Female";
student17.gradeStatic = "B+";
student17.gpaStatic = 3.5;
student17.majorStatic = "Biology";
student17.minorStatic = "Chemistry";
student17.creditsStatic = 40;
student17.emailStatic = "jane.smith@example.com";
student17.phoneNumberStatic = "555-5678";
student17.addressStatic = "456 Oak Rd";
	  
    }
}